// <auto-generated> This file is generated from version.txt. Do not edit manually.
namespace YTPlayer
{
    internal static class VersionInfo
    {
        public const string Version = "1.10.0";
        public const string AssemblyVersion = "1.10.0.0";
    }
}
