// <auto-generated> This file is generated from version.txt. Do not edit manually.
namespace YTPlayer
{
    internal static class VersionInfo
    {
        public const string Version = "2.4.4";
        public const string AssemblyVersion = "2.4.4.0";
    }
}
